/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as fakeProductIdentifierSol from "./FakeProductIdentifier.sol";
export { Product__factory } from "./Product__factory";
